### ISSUE TITLE
Not scraping all artwork

### ISSUE THREAD

**Issue by t0mtee** [pkscout/metadata.tvshows.themoviedb.org.python#102]
So I'm using this addon to try and get artwork for Game of Thrones, however lots of artwork isn't showing up. It's not just for Game of Thrones, but as an example, [this](https://www.themoviedb.org/t/p/w220_and_h330_face/tYXbVwFjFTFDp27Z1ABUxEwNHkS.jpg) isn't showing up. [Attached](https://github.com/xbmc/metadata.tvshows.themoviedb.org.python/files/10701333/kodi.log) is a debug log.

**Comment by KarellenX** [comment]
That sounds about right because not all artwork is scraped. A limit has to be set otherwise MySQL users will have problems scraping. See... https://github.com/xbmc/xbmc/issues/15768

TheMovieDatabase Python scraper for movies only scrapes 10 fanart and 10 posters

TV Shows are a lot more complicated because it has to deal with the TV Show and Seasons. So the scraper calculates the total number of artwork that can be scraped (I think it is 300?) spread across banner, clearart, clearlogo, fanart, keyart, landscape and poster **for tv show and seasons.**

Your particular image in season 7 is image 20 out of 21 (almost at bottom position), so its been cut out due to the limit on the artwork.

Either download the artwork manually, or up-vote it so its closer to the top of the list at TMDB.

**Comment by t0mtee** [comment]
I’m aware of this issue and have done the solution listed in the comments. With the TMDb Python movie scraper, you can change the image limit in the add on files, is this possible with this?

**Comment by KarellenX** [comment]
Possible, yes. How? I don't know. It is more complicated as it is a calculation, rather than a simple number you can change.

**Comment by t0mtee** [comment]
Found it. Go into settings.py, and find MAXIMAGES. Change it from 200 to a larger number (I chose 1000). Thanks for the explanation but it doesn't seem to be that complicated, unless if there are issues that will arise that I haven't seen yet.

**Comment by pkscout** [comment]
If you do this and use MariaDB as the backend database, the scraper will crash if there are too many images and the scrape will fail badly.  This is not a recommended change and others SHOULD NOT unless you are never, ever, under any circumstances going to using MariaDB.  Making this change will result in a database that will never be able to be imported into MariaDB.

I hope I've made clear that this is a Really Bad Idea.

**Comment by KarellenX** [comment]
@OsoaGH 

I completely agree with pkscout.
You have made these changes at your own discretion, even after I explained why this code is needed, and the effects on scraping without the code.

Especially as the code was designed for your **exact** setup.

Please don't come back here and start reporting broken scraping and library problems. If it does happen, you know what to do to fix it.
