### ISSUE TITLE
Episode Titles not scraped with fallback language

### ISSUE THREAD

**Issue by KarellenX** [pkscout/metadata.tvshows.themoviedb.org.python#18]
Issue reported here for the XML scraper also affects this Python scraper...

https://github.com/xbmc/repo-scrapers/issues/225

**Comment by KarellenX** [comment]
Turns out that this is a problem with TheMovieDb
![german](https://user-images.githubusercontent.com/44626605/95275175-8b95d800-0893-11eb-93e6-ee9892f26942.JPG)

**Comment by pkscout** [comment]
Can confirm. It appears if there is no translation that TMDb sends back these default episode names. What's even stranger is that that season names are in German (i.e. Staffel 1), so there is some attempt to do some basic translation, but not everywhere. I guess technically we could check the episode name if the language is not English to see if it starts with "Episode" and then grab the English instead. The worst case scenario would be a show that actually has the name "Episode xx," in which case we'd be doing an extra API call for nothing.  I'd rather see if your bug report to TMDb gets any attention.

**Comment by pkscout** [comment]
There is test code available to resolve this at:

https://github.com/xbmc/metadata.tvshows.themoviedb.org.python/tree/feature-english-fallback

It should be version 1.2.2 (Matrix only until testing complete).  I tried de-DE with Fantasy Island (the original), Battlestar Galactica (remake) and Bones.  Bones was interesting because the first two seasons of episode descriptions are not translated to German (but the episode titles are), so you get a mix of German and English that changes depending on the season. But it is an accurate reflection of what's in TMDb.

**Comment by pkscout** [comment]
Based on feedback from the forum, I'm closing this as resolved. The code has been merged into the main Matrix and Leia branches and will be included in the next update.

**Comment by KarellenX** [comment]
`I guess technically we could check the episode name if the language is not English to see if it starts with "Episode" and then grab the English instead. `

I guess this is now causing problems for users, when the episode title is actually **Episode x**

**Comment by pkscout** [comment]
I'm still trying to figure out the all the undocumented changes TMDb made to the API. Fields that used to exist if empty now sometimes don't.  Episode names used to have Episode xx as the title if there was no translated title, now they are blank. Or sometimes null.  It's a god damn mess from what I can tell.

**Comment by KarellenX** [comment]
So these are recent changes by Travis?

Is it worth contacting him again as maybe he has made some more unintentional bloopers?

**Comment by pkscout** [comment]
These are recent changes.  At this point it doesn't matter. I've rewritten all the code (at least I think so) to account for both the new way the data is being sent and the old way. So if he leaves it, we're fine. If he reverts back, we're fine. If he changes stuff again, then we'll be playing wack-a-mole again.  🤷

**Comment by martin-tarjanyi** [comment]
Unfortunately, this fix doesn't work for all languages. For example in case of Hungarian (language code `hu`) the generic title "Episode 1" is translated to Hungarian as "1. rész":
![image](https://user-images.githubusercontent.com/17810336/107862163-31151580-6e4b-11eb-837c-1c90c8b8d8df.png)

In this case the fallback is not triggered.

Although, looking at the related change it should work because overview is empty: https://github.com/xbmc/metadata.tvshows.themoviedb.org.python/blob/e7994ced3b7a5eeb7bdba751f96821a429621311/libs/tmdb.py#L217

I'm on Kodi 18.9 and the add-on (TMDb TV Shows) version is 1.1.31. What am I missing?

**Comment by pkscout** [comment]
@martin-tarjanyi, you aren't missing anything. Unfortunately TMDb made further changes to the data that's returned by the API.  It used to return the English "Episode X," then it changed to return `None`, and now it returns the translation for "Episode X." That means there is no longer any reasonable way to tell when the requested language has a generic episode number. The TMDb folks are working on adding language fallback to the API results, and it is listed as UP NEXT on their work board:

https://trello.com/b/bVlsp6wz/api

So until that change happens, the Kodi scraper will return generic episode titles for non-English languages where there is no translated episode name.

**Comment by martin-tarjanyi** [comment]
Thanks for the quick reply!
https://github.com/xbmc/metadata.tvshows.themoviedb.org.python/blob/af34f516cd5ee62e19a8c13eaf3d02457fc78620/libs/tmdb.py#L235-L245
Would it be possible to always override the episode name as well when the overview is empty? Or are there some edge cases where that wouldn't work well? Maybe episodes without overview or episodes with translated name but not translated overview?  I guess I answered my question 😄
