### ISSUE TITLE
Artwork Settings

### ISSUE THREAD

**Issue by KarellenX** [pkscout/metadata.tvshows.themoviedb.org.python#21]
As raised in this issue report here... https://github.com/xbmc/metadata.themoviedb.org.python/issues/56

The new core settings for artwork have been merged into v19 allowing a user to select None, Custom, Basic and Maximum artwork levels. Is it still necessary to keep artwork settings in scrapers also? 

The PR for the new settings by @rmrector can be found here... https://github.com/xbmc/xbmc/pull/18072 
@DaveTBlake has also merged the similar settings for the music library artwork... https://github.com/xbmc/xbmc/pull/18173

It would be more streamlined to have a single step to set artwork, rather than the current two step system we have now of 
1. Scraper artwork settings and
2. advancedsettings.xml artwork tags (v18) / the new artwork settings (v19)

As the scraper artwork settings have no effect if the second step is not implemented, then why not leave these settings enabled by default and remove them from the settings page so they are not visible to the user. 

A user then only needs to set the second step, and from their point of view it is only a single step to get artwork.

**Comment by pkscout** [comment]
I'll be happy to do this on the TV show scraper side.  I read the entirety of both PRs, and while I understand all this in concept, I have no idea how to implement it in practice.  I think I'm going to have to wait until @rmrector does something on the movie scraper side so that I can see how this works and make sure the implementation is consistent between the movie and TV show scraper.

**Comment by KarellenX** [comment]
Sure. Thank you @pkscout

**Comment by pkscout** [comment]
addressed with 676984ef2f5869ea3bac57264dbcfaf7b5d0e69e. This has been merged into the main Matrix branch  (will be a Matrix only feature) and included in the next update.
