### ISSUE TITLE
TV Show regex

### ISSUE THREAD

**Issue by GeorgeBell1982** [pkscout/metadata.tvshows.themoviedb.org.python#38]
Good day,

I picked up that my tv show episodes where not loading correctly on Kodi, pulled the code and found that I needed to add a regex to the data_utils for getting the show id correctly. I wanted to create a branch and PR, but I dont have rights here.

The regex to be added is:
r"(thetvdb)\.com/.*?'id':(\d+)",                      # TheTVDB_http_link

This caters for the url passed in the following format:
"https://api.thetvdb.com/login?{'apikey':'5FEC454623154441','id':350667}|Content-Type=application/json"

I am attaching the test file and the changed file. (please rename to .py)
I would really appreciate it if this can be implemented and released.

Thank you

[kodi_regex_test.txt](https://github.com/xbmc/metadata.tvshows.themoviedb.org.python/files/6403440/kodi_regex_test.txt)
[data_utils.txt](https://github.com/xbmc/metadata.tvshows.themoviedb.org.python/files/6403442/data_utils.txt)

**Comment by pkscout** [comment]
Please make sure you are using the most current version of the scraper. That regex has already been implemented.

**Comment by GeorgeBell1982** [comment]
Hi @pkscout , 

there's a subtle difference between the one thats already there and the one I need. 
The first one below is what you have and the second one is the one that conforms to the url sent by Kodi.
    r'(thetvdb)\.com/.*?"id":(\d+)',                      # TheTVDB_http_link
    r"(thetvdb)\.com/.*?'id':(\d+)",                      # TheTVDB_http_link

If the id is in double quotes, it fails, it needs to be in single quotes.

Thanks

**Comment by KarellenX** [comment]
@GeorgeBell1982 

Thanks for your comments. 

Could you please provide a debuglog which captures the issues you are experiencing with scraping.

Thanks.

**Comment by GeorgeBell1982** [comment]
@KarellenX ,

Please find attached, you will see that the series is trying to match on the regex, I added a print that prints the nfo with each regex test.

Hope this helps.
[kodi.log](https://github.com/xbmc/metadata.tvshows.themoviedb.org.python/files/6403678/kodi.log)

**Comment by pkscout** [comment]
Where are those URLs coming from? Are the in actual NFO files, or are they stored in the database?  According to the TVDB documentation at:

https://api.thetvdb.com/swagger

The JSON in the URL must be in double quotes, so I'm trying to figure out if at some point you got bad URLs stored in your database or if your NFO files aren't correct.

**Comment by GeorgeBell1982** [comment]
@pkscout I use an app called tvrename (https://www.tvrename.com/) to move my shows and rename them, it also generates NFO's. 

The nfo has a line like follows, which I believe Kodi picks up.
```
<episodeguide>
    <url post="yes" cache="auth.json">https://api.thetvdb.com/login?{'apikey':'5FEC454623154441','id':323168}|Content-Type=application/json</url>
  </episodeguide>

```
My first approach was to delete all NFO's, but Kodi still used the same entry (caching?), as I suspected them to be the source of my troubles.

If the NFO is the problem, and I have deleted them, is there a way to "tell" Kodi to clear its cache? Without clearing the whole series db?

The single or double quotes wouldn't make a difference in the API, as a JSON parse would still give you a string? But it obviously makes a big difference when running a regex search.

**Comment by pkscout** [comment]
It looks like TV Rename only supports TVDB, and they are generating a URL that may work in some cases but does not match the API as defined by TVDB.  In the long term you should ask them to either add support for The Movie Database or at least fix the URL so that it matches the spec defined in the API.

In the short term, if you fix the NFO files manually I think you can just refresh the show to get the updated URL. That might also work if you just flat out delete the NFO files and then refresh the show and tell it to use information from the internet. If you have lots of shows, you might be better of just deleting all the NFO files, removing all the shows in question from your library, and then re-adding them.

The parsing of alternate show IDs was meant as a transitional aid for folks moving from one of the old scrapers. It wasn't meant as a long term way of using alternate IDs, and I don't think we're going to start adding custom parsing rules for all these third party NFO generation tools.  If you need to keep using that tool and they don't fix the URL, you might need to switch to the TVDB scraper, as it will probably work with that out of spec URL. Just be aware that TVDB is releasing a new API soon that will may require pay for use.

I'm going to go ahead and close this.

**Comment by GeorgeBell1982** [comment]
@pkscout Just as last note on this, I have downloaded the tvrename code base and found the following link in their creation of the nfo file.
[NFO format](https://forum.kodi.tv/showthread.php?tid=323588)

I will change their code, with a PR and compile to match your regex in the meanwhile. Thanks for all the feedback.
