### ISSUE TITLE
Content Ratings / Certification / MPAA

### ISSUE THREAD

**Issue by KarellenX** [pkscout/metadata.tvshows.themoviedb.org.python#5]
Could you please add country specific Certifications and Prefix.

TheMovieDB allows for certifications from multiple countries as shown in the below example.
The prefix is user edited and allows user to add the correct prefix to work with their chosen skin (though most users don't know this and always end up with the USA ratings)

Might be of use... https://github.com/xbmc/metadata.themoviedb.org.python/pull/2

![certifications](https://user-images.githubusercontent.com/44626605/93050108-a070b880-f6a5-11ea-951d-98b77ad92b67.JPG)

![certification](https://user-images.githubusercontent.com/44626605/93050145-acf51100-f6a5-11ea-9f3a-af45b19db4e6.jpg)

**Comment by pkscout** [comment]
completed and pushed to main branch with a31da513fc9c0098c96e8cfa589b860bde286e53

**Comment by KarellenX** [comment]
Hi @pkscout 

Downloaded your latest main branch. A little glitch somewhere.

Version installed (which I will check first from now on ;) )...
![tvdb1](https://user-images.githubusercontent.com/44626605/93148934-7ae0bf00-f738-11ea-8ce0-203722d71d40.jpg)

When I adjust my settings via Settings>Add-ons, all looks good
(remember this only adjusts the default settings here, and not existing Sources)
![tvdb3](https://user-images.githubusercontent.com/44626605/93149003-98ae2400-f738-11ea-8b2d-8a161a816255.jpg)

When I try to adjust my settings on a Source, I get this...
![tvdb2](https://user-images.githubusercontent.com/44626605/93149034-a499e600-f738-11ea-8f8b-b119a7e61d31.jpg)

**Comment by pkscout** [comment]
I think that may be a core Kodi bug (or at least a strange expected behavior). I can duplicate that with an existing source that I had defined using the scraper before I added any settings. But if I create a new source then I see the settings, and I see them if I go back and edit a source. If I change one of those existing "bad" sources to none and save, then change it back to TV Shows using tmdb python scraper, the settings come up. So it's like the scraper only knows whether it has settings at creation. The good news is that even if we can't get it fixed, the bug should only affect you and I, since we're probably the only ones who installed the scrapper before there were settings.

**Comment by KarellenX** [comment]
Oh, of course. The scraper was existing so there was no settings string
![settings1](https://user-images.githubusercontent.com/44626605/93151770-23dee800-f740-11ea-80fa-27e38fa63871.JPG)

Then changing scraper and back again forced the new settings and all works again
![settings2](https://user-images.githubusercontent.com/44626605/93151776-28a39c00-f740-11ea-909e-4064d713dc27.JPG)

No fix needed.
Thanks
